### ISSUE TITLE
Filtering by DateTime

### ISSUE THREAD

**Issue by dearcodes** [kendo-labs/dlinq-helpers#6]
I'm currently trying to filter by date but getting this error:

```
Operator '=' incompatible with operand types 'DateTime' and 'String'
```

Is there any problems with DateTime Filtering or I'm doing it wrong?

Thanks in advanced,

D.

**Comment by akorchev** [comment]
No known issues. Probably the date isn't properly deserialized from JSON.

**Comment by dearcodes** [comment]
Thanks for the response @akorchev .

So you think it's the JSON response from the filter event in the grid? The response will unequivocally set the date value to string and then compare it depending on the operator.

So the error is pretty straightforward 

```
Operator '=' incompatible with operand types 'DateTime' and 'String'
```

The filter parameter in the toDataSource(take, skip, sort, filter) result is comparing String with DateTime. 

I've also checked how the filter value is passed to the Filter and the value is admissible (""2014-05-02T06:00:00Z"").

This is where the error is triggered

```
QueryableExtensions.cs
// Use the Where method of Dynamic Linq to filter the data
                queryable = queryable.Where(predicate, values);
```

The parameter values passed to the Where statement

```
Predicate : "(StartedAt > @0)"
Values[2] : "2014-05-02T06:00:00Z" 
```

I keep getting this error and is very confusing if anyone knows what it could be,  the help is very appreciated.

Thanks,

D.

**Comment by akorchev** [comment]
I know why this happens. By default ASP.NET MVC uses the JavaScriptSerializer for binding models which are sent as JSON. However JavaScriptSerializer doesn't support dates serialized by JSON.stringify. The only solution I have found is to use a custom ValueProviderFactory which understands JavaScript dates. I found one [here](https://json.codeplex.com/discussions/347099).

To use it register it in your application start:

```
        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();

            RegisterGlobalFilters(GlobalFilters.Filters);
            RegisterRoutes(RouteTable.Routes);

            ValueProviderFactories.Factories.Remove(ValueProviderFactories.Factories.OfType<JsonValueProviderFactory>().FirstOrDefault());
            ValueProviderFactories.Factories.Add(new JsonNetValueProviderFactory());
        }
```

Here is the complete code of JsonNetValueProviderFactory

```
 public class JsonNetValueProviderFactory : ValueProviderFactory
    {
        public override IValueProvider GetValueProvider(ControllerContext controllerContext)
        {
            // first make sure we have a valid context
            if (controllerContext == null)
                throw new ArgumentNullException("controllerContext");

            // now make sure we are dealing with a json request
            if (!controllerContext.HttpContext.Request.ContentType.StartsWith("application/json", StringComparison.OrdinalIgnoreCase))
                return null;

            // get a generic stream reader (get reader for the http stream)
            StreamReader streamReader = new StreamReader(controllerContext.HttpContext.Request.InputStream);
            // convert stream reader to a JSON Text Reader
            JsonTextReader JSONReader = new JsonTextReader(streamReader);
            // tell JSON to read
            if (!JSONReader.Read())
                return null;

            // make a new Json serializer
            JsonSerializer JSONSerializer = new JsonSerializer();
            // add the dyamic object converter to our serializer
            JSONSerializer.Converters.Add(new ExpandoObjectConverter());

            // use JSON.NET to deserialize object to a dynamic (expando) object
            Object JSONObject;
            // if we start with a "[", treat this as an array
            if (JSONReader.TokenType == JsonToken.StartArray)
                JSONObject = JSONSerializer.Deserialize<List<ExpandoObject>>(JSONReader);
            else
                JSONObject = JSONSerializer.Deserialize<ExpandoObject>(JSONReader);

            // create a backing store to hold all properties for this deserialization
            Dictionary<string, object> backingStore = new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase);
            // add all properties to this backing store
            AddToBackingStore(backingStore, String.Empty, JSONObject);
            // return the object in a dictionary value provider so the MVC understands it
            return new DictionaryValueProvider<object>(backingStore, CultureInfo.CurrentCulture);
        }

        private static void AddToBackingStore(Dictionary<string, object> backingStore, string prefix, object value)
        {
            IDictionary<string, object> d = value as IDictionary<string, object>;
            if (d != null)
            {
                foreach (KeyValuePair<string, object> entry in d)
                {
                    AddToBackingStore(backingStore, MakePropertyKey(prefix, entry.Key), entry.Value);
                }
                return;
            }

            IList l = value as IList;
            if (l != null)
            {
                for (int i = 0; i < l.Count; i++)
                {
                    AddToBackingStore(backingStore, MakeArrayKey(prefix, i), l[i]);
                }
                return;
            }

            // primitive
            backingStore[prefix] = value;
        }

        private static string MakeArrayKey(string prefix, int index)
        {
            return prefix + "[" + index.ToString(CultureInfo.InvariantCulture) + "]";
        }

        private static string MakePropertyKey(string prefix, string propertyName)
        {
            return (String.IsNullOrEmpty(prefix)) ? propertyName : prefix + "." + propertyName;
        }
    }
```

**Comment by dearcodes** [comment]
I had already made a workaround but this is much more cleaner!

Great @akorchev that solved the problem! 

Thanks!!

D.

**Comment by Katarina1330** [comment]
I have to issues with Kendo grid filtering. I'm using Kendo 2015.2.902 version and installed Kendo.DynamicLinq 1.1.2.0. 

First issue is related on parameters which I received from Kendo grid. Filter data are deserialized into Kendo Filter class in my controller action. After deseralization Value property became array of strings and ToDataSourceResult method throws exception: "Operator '>' incompatible with operand types 'DateTimeOffset' and 'String[]".  It was happened for any filtering. I temporarily fixed by removing array and injecting string.

Second issue happened after I "fixed" first one. Method ToDataSourceResult throws exception: "Operator '>' incompatible with operand types 'DateTimeOffset' and 'DateTimeOffset' ".  

I followed http://blog.codebeastie.com/kendo-grid-sorting-and-filtering/ and implemented my controller action as explained. Also I implemented JsonNetValueProviderFactory as described here. 

Do you know  how can I fix that and is it because of different Kendo versions?
